name: practice_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.1
  getwidget: ^5.0.0
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  animated_bottom_navigation_bar: ^1.3.3
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.1
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  flutter_chat_ui: ^1.6.15
  file_picker: ^8.3.5
  syncfusion_flutter_pdf: ^28.2.5
  flutter_riverpod: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
